"""Generate `analysis/public_api.md` from `server/javelin/__init__.py`.

Walks the `__all__` list in order, pulls the first paragraph of each
symbol's docstring, and renders a grouped markdown reference. The
section groupings come from the comment markers in `__init__.py`'s
`__all__` list — re-running the script keeps the reference in sync
with the live exports.

Also documents `server.javelin.dispatch`'s public surface
(`decode_replay_message`, `encode_replay_message`, `supported_type_ids`,
`encodable_type_ids`, `DECODERS`, `ENCODERS`) since those are the
canonical entry points for routing typed messages.

Run from repo root:
    .venv/bin/python3 tools/build_api_reference.py
"""

from __future__ import annotations

import inspect
import re
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

import server.javelin as javelin  # noqa: E402
from server.javelin import dispatch  # noqa: E402


# Parse the section structure from __init__.py's __all__ block.
# Each `# heading` line above a group of "Name", entries names that
# group.
def parse_sections() -> list[tuple[str, list[str]]]:
    init_text = (REPO / "server/javelin/__init__.py").read_text()
    start = init_text.index("__all__ = [")
    block = init_text[start : init_text.index("]", start) + 1]

    sections: list[tuple[str, list[str]]] = []
    current_heading: str | None = None
    current_names: list[str] = []

    for raw_line in block.splitlines():
        line = raw_line.strip()
        if line.startswith("# "):
            if current_heading is not None:
                sections.append((current_heading, current_names))
            current_heading = line[2:].rstrip()
            current_names = []
            continue
        m = re.match(r'"([^"]+)"', line)
        if m and current_heading is not None:
            current_names.append(m.group(1))
    if current_heading is not None:
        sections.append((current_heading, current_names))
    return sections


def first_paragraph(text: str) -> str:
    """First paragraph of a docstring, collapsed to one line."""
    if not text:
        return ""
    paras = text.strip().split("\n\n")
    return " ".join(paras[0].split())


def describe(symbol_name: str):
    obj = getattr(javelin, symbol_name, None)
    if obj is None:
        return ("?", "(re-export not found at runtime)", "")
    kind = "class" if inspect.isclass(obj) else (
        "function" if callable(obj) else "value")
    doc = inspect.getdoc(obj) or ""
    summary = first_paragraph(doc)
    module = getattr(obj, "__module__", "") or ""
    return (kind, summary, module)


def render() -> str:
    out = []
    out.append("# Public API reference — `server.javelin`\n")
    out.append("Generated from `server/javelin/__init__.py`'s `__all__` "
               "list by [`tools/build_api_reference.py`](../tools/build_api_reference.py). "
               "Re-run to refresh; **do not edit this file by hand** — "
               "edits will be overwritten the next time the script runs.\n")
    out.append(
        "Most-used codec classes are re-exported through the package "
        "root for convenience (`from server.javelin import X`). The "
        "full module is also importable directly when you want a "
        "private helper or a constant the re-export skips "
        "(`from server.javelin.X import _Y`).\n"
    )
    out.append("---\n")

    # Section: dispatcher (not in __all__ — pulled in from dispatch.py)
    out.append("## Central dispatcher\n")
    out.append(
        "The dispatcher in `server.javelin.dispatch` provides type-id-"
        "indexed encode/decode routing for all 40 captured wire-types "
        "plus 0x5d1 (state-10 trigger). It's the canonical entry point "
        "for any code that wants a single call instead of importing "
        "each per-type module.\n"
    )
    for name in (
        "decode_replay_message",
        "encode_replay_message",
        "supported_type_ids",
        "encodable_type_ids",
        "DECODERS",
        "ENCODERS",
    ):
        obj = getattr(dispatch, name, None)
        if obj is None:
            continue
        kind = (
            "class" if inspect.isclass(obj) else
            "function" if callable(obj) else
            "value"
        )
        if kind == "value":
            # Skip the class-level docstring inherited from `dict` etc;
            # render an instance-aware summary instead.
            if name == "DECODERS":
                summary = f"`dict[int, decoder]` — {len(obj)} entries; the type-id → decoder routing table."
            elif name == "ENCODERS":
                summary = f"`dict[int, encoder]` — {len(obj)} entries; the type-id → encoder routing table."
            else:
                summary = f"`{type(obj).__name__}` — {len(obj) if hasattr(obj, '__len__') else '?'} entries."
        else:
            doc = inspect.getdoc(obj) or ""
            summary = first_paragraph(doc)
        out.append(f"- **`{name}`** (`{kind}`) — {summary}")
    out.append("")

    sections = parse_sections()
    for heading, names in sections:
        out.append(f"## {heading}\n")
        for name in names:
            kind, summary, module = describe(name)
            if module:
                module_short = module.replace("server.javelin.", "")
                module_tag = f"  ⟨`{module_short}`⟩"
            else:
                module_tag = ""
            if not summary:
                summary = "_(no docstring)_"
            out.append(f"- **`{name}`** (`{kind}`){module_tag} — {summary}")
        out.append("")

    out.append("---\n")
    out.append(
        "_Last regenerated automatically. Counts: "
        f"{sum(len(n) for _, n in sections)} re-exports across "
        f"{len(sections)} sections, plus 6 dispatcher entry points._"
    )
    return "\n".join(out) + "\n"


def main() -> int:
    out_path = REPO / "analysis" / "public_api.md"
    text = render()
    out_path.write_text(text)
    print(f"wrote {out_path} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
